---
title: "About The Data"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: html_document
---
<style type="text/css">
.navbar {
  background-color:#1db954;
}
.main-container {
  max-width: 1600px;
  font-size: 16px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r doc-setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import-libraries, include = FALSE}
library(tidyverse)
library(dplyr)
library(knitr)
library(kableExtra)
library(plotly)
```

```{r import-data, echo = FALSE, message = FALSE}
spotify_data <- read_csv("https://raw.githubusercontent.com/hotz1/JSC370-HW5/main/spotify_data_full.csv")
```

```{r countries-table, echo = FALSE, message = FALSE}
countries <- table(spotify_data$Country)
countries <- countries / 200
knitr::kable(countries, caption = "Number of Top 200 Weekly Tracks lists available on the Spotify Charts website per country",
             col.names = c("Country Name", "Weeks of Data")) %>%
  kableExtra::scroll_box(height = '800px')
```